package com.udea.persistencia;
// Generated 17-mar-2020 20:44:57 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="ciudad"
    ,catalog="climadb"
)
public class Ciudad  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int codigoPostal;
     private int indicador;

    public Ciudad() {
    }

    public Ciudad(int id, String nombre, int codigoPostal, int indicador) {
       this.id = id;
       this.nombre = nombre;
       this.codigoPostal = codigoPostal;
       this.indicador = indicador;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo_postal", nullable=false)
    public int getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(int codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="indicador", nullable=false)
    public int getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(int indicador) {
        this.indicador = indicador;
    }




}


